### ISSUE TITLE
Switch to yaml config format

### ISSUE THREAD

**Issue by Fogapod** [unitystation/unitystation#5626]
### Description
Currently UnityStation uses multiple json configs with OverTheTopVerboseVariableNamesInsideOfThemWhichAreStillNotAlwaysClear.

Json is fine and it works, but we could do much better with yaml.
There are some arguments against this change:
- json is already used by project, some code will need to be rewritten
- it's easier to modify yaml files programmatically
- better protected against copypastes because indents can't be messed up?

But in my opinion, in the long run, these are more important:
- yaml is a superset of json, so you do not lose anything by switching
- much more readable by humans, yaml doesn't have syntatic garbage like commas and quotes
- comments exist
- variables are grouped into sections instead of using obscure 39 character variable names: `DiscordWebhookEnableBanKickAnnouncement`
- all configs are in one file, which makes it easier to migrate it

Here is my initial draft of theoretical config:
`config.yaml`
```yaml
Server:
  Name: StagingEU02

  Description: |
    Put your long and beautiful server description
    and server rules into this section.

    You should probably include brief rules in there.

  Links:
    DiscordInvite: https://discord.gg/tFcTpBp

  # Credentials for being included into official UnityStation Hub server list
  Hub:
    User: admin
    Password: qwerty

  Webhooks:
    Enabled: false

    Discord:
      OOC:
        URL: https://example.org
        MentionsID: 677800847391850496
      Admin:
        URL: https://example.org
      Annoucements:
        URL: https://example.org
        BanKickMessages: false
      AllChat:
        URL: https://example.org
        OOCMessages: false
      AdminLog:
        URL: https://example.org
      Errors:
        URL: https://example.org

  Downloads:
    Windows: https://example.org/win.zip
    OSX: https://example.org/osx.zip
    Linux: https://example.org/linux.zip

  RemoteConsole:
    Port: 7778
    Password: 12345678

Maps:
  LowPop:
    Rotation:
      - FallStation
      - SquareStation
  MedPop:
    MinPlayers: 15
    Rotation:
      - OutpostStation
      - BoxStationV1
  HighPop:
    MinPlayers: 30
    Rotation:
      - OutpostStation
      - BoxStationV1

GameSettings:
  # Minimum amount of players to begin countdown for starting game
  MinPlayers: 1

  InitialGamemode: Random

  # I don't know what is this
  RoundsPerMap: 10

  Rules:
    RandomEvents: true
    LavaLand: true
    Respawn: false
    Gibbing: false
    ShuttleGibbing: false

  Timings:
    PreRound: 120
    RoundEnd: 60

# Used for automatically updating config, do not modify manually
ConfigVersion: 1
```

I included every variable from all configs I could find excluding admin configs (some of which could benefit from yaml too, for example admin list. The reason why I did not include them is to allow more granular permission management for individual files)

#### Additional comments
`Webhooks` section may have `Enabled` switch on any level (enable/disable Discord, enable/disable individual source like OOC)

I used uppercase camelCase for variable names because C#, but usually yaml files are in snake_case.

Note the `ConfigVersion` variable at the end. It could be used for migrating configs. Alternative could be a separate file:
`config-version.yaml`
```
1
```

This is just the first draft of config, so I want to know what I did wrong and what needs to be changed.
