### ISSUE TITLE
Tests should run for every PR but simply pass if no unity project files were changed

### ISSUE THREAD

**Issue by corp-0** [unitystation/unitystation#7902]
### Description
The way it works currently is only triggering the workflow when a file was changed in a particular path, which means I have to disable branch protections to be able to merge PRs that don't modify the UnityProject folder. 

```yml
on:
  push:
    branches:
      - develop
    paths:
      - "Tools/UnityLicense.ulf"
      - "UnityProject/**"
      - ".github/workflows/**"
      - "Docker/**"
  pull_request:
    branches:
      - develop
    paths:
      - "Tools/UnityLicense.ulf"
      - "UnityProject/**"
      - ".github/workflows/**"
````
[relevant file](https://github.com/unitystation/unitystation/blob/develop/.github/workflows/test.yml)

It should actually always trigger the workflow but instantly pass when no file inside the UnityProject was modified, so we don't have to go back and disable branch protections every time which is prone to error eventually.
